[theme]
base="dark"
primaryColor="#F63366"
backgroundColor="#041534"  # or any other dark color you prefer
secondaryBackgroundColor="#fb6f92"  # or any other dark color you prefer
textColor="#fac003"  # or any other light color you prefer
font="Segoe UI"  # or any other font that you prefer

